// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: asr.proto

package asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw PCM audio data, float32 little-endian, mono channel
	AudioData []byte `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	// Sample rate of the audio (e.g. 16000 for 16 kHz)
	SampleRate int32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Optional language hint (e.g. "English", "Chinese"). Empty = auto-detect.
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	// When true, signals the end of the stream. Server will flush and finalize.
	IsFinal       bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AudioChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type TranscriptChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Partial or final transcribed text
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Detected or hinted language
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// When true, this is the final consolidated transcription for this stream
	IsFinal       bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptChunk) Reset() {
	*x = TranscriptChunk{}
	mi := &file_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptChunk) ProtoMessage() {}

func (x *TranscriptChunk) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptChunk.ProtoReflect.Descriptor instead.
func (*TranscriptChunk) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptChunk) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscriptChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\x03asr\"\x83\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\"\\\n" +
	"\x0fTranscriptChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal2K\n" +
	"\n" +
	"ASRService\x12=\n" +
	"\x10TranscribeStream\x12\x0f.asr.AudioChunk\x1a\x14.asr.TranscriptChunk(\x010\x01B0Z.github.com/smartiva/qwen3-asr-client/proto;asrb\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asr_proto_goTypes = []any{
	(*AudioChunk)(nil),      // 0: asr.AudioChunk
	(*TranscriptChunk)(nil), // 1: asr.TranscriptChunk
}
var file_asr_proto_depIdxs = []int32{
	0, // 0: asr.ASRService.TranscribeStream:input_type -> asr.AudioChunk
	1, // 1: asr.ASRService.TranscribeStream:output_type -> asr.TranscriptChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
